name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: golang:1.16
    steps:
    - uses: actions/checkout@v2

    - name: Install TinyGo 0.18.0
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v0.18.0/tinygo_0.18.0_amd64.deb
        dpkg -i tinygo_0.18.0_amd64.deb

    - name: Build
      run: make build

    - name: Run tests
      run: make test
